-- Get associated AANs for CONDO PIDs
-- Add AANs to AR PID condo table

DROP TABLE AR_STORMWATER_CONDO_AAN_SAP;

CREATE TABLE AR_STORMWATER_CONDO_AAN_SAP 
AS (
	SELECT TRIM(l.AAN) as "ACCTNO", a.PIDRELATE, a.pid, a.arcode
    FROM AR_STORMWATER_CONDO_in_SAP a, LINNS_PIDAANTAX l
    WHERE a.pidrelate = l.pid
);

commit;

DELETE FROM AR_STORMWATER_CONDO_AAN_SAP
WHERE ACCTNO IS NULL;

commit;