DROP TABLE AR_STORMWATER_FINAL_SAP;

CREATE TABLE AR_STORMWATER_FINAL_SAP
(
	   PID VARCHAR2 (8),
       ACCTNO VARCHAR2(24),
       ARCODE VARCHAR2(4)
);
   
INSERT INTO AR_STORMWATER_FINAL_SAP
       (PID, ACCTNO, ARCODE)
       SELECT PID, ACCTNO, ARCODE
       FROM AR_STORMWATER_AAN_SAP;
	   
INSERT INTO AR_STORMWATER_FINAL_SAP
       (PID, ACCTNO, ARCODE)
       SELECT PIDRELATE, ACCTNO, ARCODE 
	   FROM AR_STORMWATER_CONDO_AAN_SAP;
	   
commit;