prompt ....Running ar_regtrans1_pid_SAP.....
@ar_StormWater1_pid_SAP.sql;
prompt ....Running ar_regtrans2_AAN_SAP.....
@ar_StormWater2_AAN_SAP.sql;
prompt ....Running ar_regtrans3_CONDO_in_SAP.....
@ar_StormWater3_CONDO_in_SAP.sql;
prompt ....Running ar_regtrans4_CONDO_AAN_SAP.....
@ar_StormWater4_CONDO_AAN_SAP.sql;
prompt ....Running ar_regtrans5_final_SAP.....
@ar_StormWater5_final_SAP.sql;
--Clean up temp files
--@ar_regtrans6_clean_SAP.sql;
exit;