"""
    - These will be used as keywords to compare to the ownership of parcels.
    Ex) A parcel will be flagged as federal or provincial if it's contains a subset of one of the owners listed below.
"""

FED_OWNERS = [
    'CANADA MORTGAGE & HOUSING CORP', 'CANADA MORTGAGE AND HOUSING CORP',
    'CANADA MORTGAGE AND HOUSING CORPORATION', 'CANADA POST', 'CANADIAN COAST GUARD', 'CANADIAN GOVERNMENT',
    'CANADIAN HERITAGE, PARKS CANADA',
    'CENTRAL MORTAGE AND HOUSING CORPORATION', 'CENTRAL MORTGAGE AND HOUSING CORPORATION',

    'FISHERIES & OCEANS', 'FISHERIES AND OCEANS', 'HER MAJESTY THE QUEEN', 'HER MAJESTY THE QUEEN CANADA',
    'HER MAJESTY THE QUEEN IN RIGHT OF CANADA',
    'HIS MAJESTY THE KING CANADA',
    'NATIONAL DEFENCE', 'PARKS CANADA', 'VIA RAIL'
]

PROV_OWNERS = [
    'ATTORNEY GENERAL PROVINCE OF NOVA SCOTIA',
    'DEPARTMENT OF EDUCATION AND EARLY CHILDHOOD DEVELOPMENT',
    'DEPARTMENT OF TRANSPORTATION AND ACTIVE TRANSIT',
    'HIS MAJESTY THE KING IN RIGHT OF THE PROVINCE OF NOVA SCOTIA',
    'HIS MAJESTY THE KING IN THE RIGHT OF THE PROVINCE OF NOVA SCOTIA',
    'NOVA SCOTIA FARM LOAN BOARD', 'NS DEPARTMENT',
    'NS DEPARTMENT OF MUNCIPAL AFFAIRS AND HOUSING', 'NS DEPT', 'HER MAJESTY THE QUEEN IN RIGHT OF THE PROVINCE OF NOVA SCOTIA'
]

NON_PROV_FED_OWNERS = [
    ',', 'ASSOCIATION', 'CANADIAN NATIONAL RAILWAYS',
    'CANADIAN PROPERTY HOLDINGS (NOVA SCOTIA) INC', 'CLUB', 'COMPANY', 'COOPERATIVE', 'CORP', 
    'COUNCIL OF MILLBROOK FIRST NAT', 'COUNTY', 'DALHOUSIE', 'HALIFAX REGIONAL MUNICIPALITY', 
    'HALIFAX REGIONAL WATER COMMISSION', 'HALL', 'INC.', 'INCORPORATED',
    'INDIAN AFFAIRS',
    'INDIAN AND NORTHERN AFFAIRS',
    'INDIAN AND NORTHERN AFFAIRS CANADA',
    'INVESTMENTS', 'LIMITED', 'LTD', 'MARRIOTT',
    'MUISE, JUDY ANN',
    'NATURE CONSERVANCY OF CANADA',
    'NAV CANADA', 'NOVA SCOTIA NATURE TRUST', 'OWNER UNKNOWN', 'PRESTON AREA HOUSING FUND',
    'ROBINSON, AMY MARIE',
    'SCHOOL', 'UNIVERSITY',
    'WESTERKIRK', 'WILD COAST DEVELOPMENT ULC'
]
