[GIS_DATA]

# UPDATE ME
PARCEL_DATA_EXTRACT_DIR = T:\work\giss\monthly\202502feb\gallaga\parcels\HRM_29348

PARCEL_LOAD_DIR = C:\Workspace\Parcel_Load\Scratch

SDE_RW = E:\HRM\Scripts\SDE\SQL\Prod\prod_RW_sdeadm.sde
SDE_RO = E:\HRM\Scripts\SDE\SQL\Prod\prod_RO_sdeadm.sde

PARCEL_POINT_RW = %(SDE_RW)s/SDEADM.LND_parcel_point
PARCEL_POINT_SINGLE_RW = %(SDE_RW)s/SDEADM.LND_parcel_point_single
PARCEL_POINT_OLD_SDE_RW = %(SDE_RW)s/SDEADM.LND_PARCEL_POINT_OLD

SDEADM_LND_ghosted_parcel_line = %(SDE_RW)s/SDEADM.LND_ghosted_parcel_line
SDEADM_LND_parcel_line = %(SDE_RW)s/SDEADM.LND_parcel_line
SDEADM_LND_parcel_polygon = %(SDE_RW)s/SDEADM.LND_parcel_polygon
SDEADM_parcel_label = %(SDE_RW)s/SDEADM.LND_parcel_point_single
LND_GHOSTED_PARCEL_LINE_RW = %(SDE_RW)s/SDEADM.LND_ghosted_parcel_line
LND_PARCEL_LINE_RW = %(SDE_RW)s/SDEADM.LND_parcel_line
LND_PARCEL_POLYGON_RW = %(SDE_RW)s/SDEADM.LND_parcel_polygon

LINNS_PIDMSTRS_SDE_RW = %(SDE_RW)s/SDEADM.LINNS_PIDMSTRS
LINNS_ALL_SDE_RW = %(SDE_RW)s/SDEADM.LINNS_ALL
LINNS_ALL_STAGE_RW = %(SDE_RW)s/SDEADM.LINNS_ALL_STAGE

LINNS_ALL_SDE_RO = %(SDE_RO)s/SDEADM.LINNS_ALL
LINNS_PIDMSTRS_SDE_RO = %(SDE_RO)s/SDEADM.LINNS_PIDMSTRS

SDEADM_pidaantax = %(SDE_RW)s/SDEADM.LINNS_PIDAANTAX
SDEADM_pidnames = %(SDE_RW)s/SDEADM.LINNS_PIDNAMES
SDEADM_pidrelate = %(SDE_RW)s/SDEADM.LINNS_PIDRELATE

PIDMSTRS_DBF = %(PARCEL_LOAD_DIR)s/pidmstrs.dbf

SDEADM_PID_Locator = %(SDE_RW)s/SDEADM.PID_Locator
SDEADM_GSA_Polygon = %(SDE_RW)s/SDEADM.ADM_gsa_boundaries/SDEADM.ADM_gsa_polygon

[EMAIL]
server=mailer.halifax.ca
sender=noreply@halifax.ca
recipients=potterm@halifax.ca,gallaga@halifax.ca

