[SDSF_SETTINGS]
sdsf = T:\work\giss\monthly\202609sep\gallaga\HRFE Target Hazard\Step1\HRFE Target Hazard 1 Analysis Results.xlsx
sheet_name = "DATASET DETAILS"
SDSF_IGNORE_FIELDS = ["OBJECTID", "GLOBALID", "SHAPE", "SHAPE_AREA", "SHAPE_LENGTH"]

[FEATURE_SETTINGS]
add_editor_tracking = False
enable_archiving = False
EDIT_PERMISSIONS_USERS = []

ready_to_add_to_replica = False
replica_name = BLD_LND_Rosde

subtypes = False
topology_dataset = False
subtype_field =
subtype_domains = {}

# Optional alias override. If blank, uses 'Alias: ...' from the SDSF, then the METADATA Data Source Name
alias =

unique_id_fields = []

# Attribute indexes only (no sequence or attribute rule), ex) ["BL_ID"]
index_fields = ["BL_ID"]

[NEW_DOMAIN_TYPES]
# You can uncomment and define these as needed
;LND_service_provider_type = TEXT
;LND_grass_sources = TEXT
;LND_fac_snow_contract_group = SHORT
;LND_fac_snow_group_type = TEXT
;LND_fac_snow_vendor = SHORT
