SELECT
    TABLE_SCHEMA,
    TABLE_NAME,
	COLUMN_NAME
FROM
    INFORMATION_SCHEMA.COLUMNS
WHERE
    COLUMN_NAME IN ('FCODE') AND
	TABLE_NAME NOT LIKE 'a[0-9]%' AND
	TABLE_NAME NOT LIKE '%_evw'
ORDER BY
    TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME
;
